from rest_framework.views import APIView
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.exceptions import ValidationError

from django.db import transaction
from django.db.models import Sum
from django.db.models.functions import TruncMonth

import razorpay
from django.conf import settings

from .serializers import OrderSerializer
from .models import Order, OrderItem
from cart.models import Cart

razorpay_client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))

class CreateOrderView(APIView):
    permission_classes = [IsAuthenticated]

    @transaction.atomic
    def post(self, request):
        user = request.user

        try:
            cart = Cart.objects.get(user=user)
        except Cart.DoesNotExist:
            return Response({"detail": "Cart not found"}, status=400)

        cart_items = cart.items.select_related(
            'variant',
            'variant__product',
            'variant__size'
        )

        if not cart_items.exists():
            return Response({"detail": "Cart is empty"}, status=400)

        shipping_data = request.data.get("shipping_details", {})

        order = Order.objects.create(
            user=user,
            name=shipping_data.get("name"),
            address=shipping_data.get("address"),
            city=shipping_data.get("city"),
            postal_code=shipping_data.get("postalCode"),
            phone=shipping_data.get("phone"),
        )

        total_price = 0

        for item in cart_items:
            variant = item.variant

            if variant.stock < item.quantity:
                raise ValidationError(
                    f"Not enough stock for {variant.product.name} ({variant.size.value})"
                )

            price = variant.final_price

            OrderItem.objects.create(
                order=order,
                variant=variant,
                quantity=item.quantity,
                price=price,
            )

            variant.stock -= item.quantity
            variant.save()

            total_price += price * item.quantity

        order.total_price = total_price
        order.save()

        data = {
            "amount": int(order.total_price * 100), # Amount in paise
            "currency": "INR",
            "receipt": f"order_{order.id}"
        }

        try:
            razorpay_order = razorpay_client.order.create(data=data)
            order.razorpay_order_id = razorpay_order['id']
            order.save()

            cart_items.delete() # Clear cart only if Razorpay order is created

            return Response({
                "order_id": order.id,
                "razorpay_order_id": razorpay_order['id'],
                "amount": data['amount'],
                "currency": "INR",
                "razorpay_key": settings.RAZORPAY_KEY_ID
            })
        
        except Exception as e:
            import traceback
            traceback.print_exc() # This will print the full error in your terminal
            return Response({"detail": f"Gateway Error: {str(e)}"}, status=500)
        
class VerifyPaymentView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        payload = request.data
        
        # These are generated by the Razorpay Checkout modal
        params_dict = {
            'razorpay_order_id': payload.get('razorpay_order_id'),
            'razorpay_payment_id': payload.get('razorpay_payment_id'),
            'razorpay_signature': payload.get('razorpay_signature')
        }

        try:
            # Verify the signature
            razorpay_client.utility.verify_payment_signature(params_dict)
            
            # Update your order status
            order = Order.objects.get(razorpay_order_id=params_dict['razorpay_order_id'])
            order.status = 'PENDING' # Or a new 'PAID' status if you added one
            order.razorpay_payment_id = params_dict['razorpay_payment_id']
            order.save()

            return Response({"detail": "Payment Successful"}, status=200)
        except Exception:
            return Response({"detail": "Payment Verification Failed"}, status=400)


class AdminOrderAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    permission_classes = [IsAdminUser]


class OrderListView(generics.ListAPIView):
    serializer_class = OrderSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = Order.objects.select_related('user').prefetch_related(
            'items__variant__product',
            'items__variant__size'
        )

        if self.request.user.is_staff:
            return queryset.order_by('-created_at')

        return queryset.filter(user=self.request.user).order_by('-created_at')


class MonthlyRevenueAPIView(APIView):
    permission_classes = [IsAdminUser]

    def get(self, request):
        successful_orders = (
            Order.objects.filter(status='DELIVERED')
            .annotate(month=TruncMonth('created_at'))
            .values('month')
            .annotate(revenue=Sum('total_price'))
            .order_by('month')
        )

        chart_data = [
            {
                "month": item['month'].strftime('%b %Y'),
                "revenue": float(item['revenue'] or 0)
            }
            for item in successful_orders
        ]

        return Response(chart_data)
